// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fsm

import (
	"context"

	"github.com/kyma-project/infrastructure-manager/internal/rtbootstrapper"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRuntimeBootstrapperInstaller creates a new instance of MockRuntimeBootstrapperInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeBootstrapperInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeBootstrapperInstaller {
	mock := &MockRuntimeBootstrapperInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuntimeBootstrapperInstaller is an autogenerated mock type for the RuntimeBootstrapperInstaller type
type MockRuntimeBootstrapperInstaller struct {
	mock.Mock
}

type MockRuntimeBootstrapperInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeBootstrapperInstaller) EXPECT() *MockRuntimeBootstrapperInstaller_Expecter {
	return &MockRuntimeBootstrapperInstaller_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockRuntimeBootstrapperInstaller
func (_mock *MockRuntimeBootstrapperInstaller) Install(context1 context.Context, runtimeID string) error {
	ret := _mock.Called(context1, runtimeID)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, runtimeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuntimeBootstrapperInstaller_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockRuntimeBootstrapperInstaller_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - context1 context.Context
//   - runtimeID string
func (_e *MockRuntimeBootstrapperInstaller_Expecter) Install(context1 interface{}, runtimeID interface{}) *MockRuntimeBootstrapperInstaller_Install_Call {
	return &MockRuntimeBootstrapperInstaller_Install_Call{Call: _e.mock.On("Install", context1, runtimeID)}
}

func (_c *MockRuntimeBootstrapperInstaller_Install_Call) Run(run func(context1 context.Context, runtimeID string)) *MockRuntimeBootstrapperInstaller_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuntimeBootstrapperInstaller_Install_Call) Return(err error) *MockRuntimeBootstrapperInstaller_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuntimeBootstrapperInstaller_Install_Call) RunAndReturn(run func(context1 context.Context, runtimeID string) error) *MockRuntimeBootstrapperInstaller_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockRuntimeBootstrapperInstaller
func (_mock *MockRuntimeBootstrapperInstaller) Status(context1 context.Context, runtimeID string) (rtbootstrapper.InstallationStatus, error) {
	ret := _mock.Called(context1, runtimeID)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 rtbootstrapper.InstallationStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (rtbootstrapper.InstallationStatus, error)); ok {
		return returnFunc(context1, runtimeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) rtbootstrapper.InstallationStatus); ok {
		r0 = returnFunc(context1, runtimeID)
	} else {
		r0 = ret.Get(0).(rtbootstrapper.InstallationStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, runtimeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuntimeBootstrapperInstaller_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockRuntimeBootstrapperInstaller_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
//   - runtimeID string
func (_e *MockRuntimeBootstrapperInstaller_Expecter) Status(context1 interface{}, runtimeID interface{}) *MockRuntimeBootstrapperInstaller_Status_Call {
	return &MockRuntimeBootstrapperInstaller_Status_Call{Call: _e.mock.On("Status", context1, runtimeID)}
}

func (_c *MockRuntimeBootstrapperInstaller_Status_Call) Run(run func(context1 context.Context, runtimeID string)) *MockRuntimeBootstrapperInstaller_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuntimeBootstrapperInstaller_Status_Call) Return(installationStatus rtbootstrapper.InstallationStatus, err error) *MockRuntimeBootstrapperInstaller_Status_Call {
	_c.Call.Return(installationStatus, err)
	return _c
}

func (_c *MockRuntimeBootstrapperInstaller_Status_Call) RunAndReturn(run func(context1 context.Context, runtimeID string) (rtbootstrapper.InstallationStatus, error)) *MockRuntimeBootstrapperInstaller_Status_Call {
	_c.Call.Return(run)
	return _c
}
