// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1beta1 "github.com/kyma-project/kim-snatch/api/v1beta1"
)

// RegistryCache is an autogenerated mock type for the RegistryCache type
type RegistryCache struct {
	mock.Mock
}

// GetRegistryCacheConfig provides a mock function with no fields
func (_m *RegistryCache) GetRegistryCacheConfig() ([]v1beta1.RegistryCacheConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryCacheConfig")
	}

	var r0 []v1beta1.RegistryCacheConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]v1beta1.RegistryCacheConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []v1beta1.RegistryCacheConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1beta1.RegistryCacheConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegistryCache creates a new instance of RegistryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryCache {
	mock := &RegistryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
