// Code generated by hand (following mockery patterns). DO NOT EDIT.
//go:build !ignore_autogenerated

package mocks

import (
	"context"

	"github.com/kyma-project/infrastructure-manager/pkg/auditlog"
	"github.com/stretchr/testify/mock"
)

// DataProvider is a mock implementation of auditlog.DataProvider
type DataProvider struct {
	mock.Mock
}

// ReserveAuditLog provides a mock function with given fields: ctx, providerRegion, runtimeID
func (m *DataProvider) ReserveAuditLog(ctx context.Context, providerRegion string, runtimeID string) error {
	ret := m.Called(ctx, providerRegion, runtimeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, providerRegion, runtimeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDedicatedAuditLogData provides a mock function with given fields: ctx, runtimeID
func (m *DataProvider) GetDedicatedAuditLogData(ctx context.Context, runtimeID string) (auditlog.AuditLogData, error) {
	ret := m.Called(ctx, runtimeID)

	var r0 auditlog.AuditLogData
	if rf, ok := ret.Get(0).(func(context.Context, string) auditlog.AuditLogData); ok {
		r0 = rf(ctx, runtimeID)
	} else {
		r0 = ret.Get(0).(auditlog.AuditLogData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runtimeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimDedicatedAuditLogData provides a mock function with given fields: ctx, runtimeID
func (m *DataProvider) ClaimDedicatedAuditLogData(ctx context.Context, runtimeID string) (auditlog.AuditLogData, error) {
	ret := m.Called(ctx, runtimeID)

	var r0 auditlog.AuditLogData
	if rf, ok := ret.Get(0).(func(context.Context, string) auditlog.AuditLogData); ok {
		r0 = rf(ctx, runtimeID)
	} else {
		r0 = ret.Get(0).(auditlog.AuditLogData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runtimeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSharedAuditLogData provides a mock function with given fields: ctx, providerType, region
func (m *DataProvider) GetSharedAuditLogData(ctx context.Context, providerType string, region string) (auditlog.AuditLogData, error) {
	ret := m.Called(ctx, providerType, region)

	var r0 auditlog.AuditLogData
	if rf, ok := ret.Get(0).(func(context.Context, string, string) auditlog.AuditLogData); ok {
		r0 = rf(ctx, providerType, region)
	} else {
		r0 = ret.Get(0).(auditlog.AuditLogData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, providerType, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseDedicated provides a mock function with given fields: ctx, runtimeID
func (m *DataProvider) ReleaseDedicated(ctx context.Context, runtimeID string) error {
	ret := m.Called(ctx, runtimeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, runtimeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDataProvider creates a new instance of DataProvider mock
func NewDataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataProvider {
	mock := &DataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
