// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rtbootstrapper

import (
	"context"

	"github.com/kyma-project/infrastructure-manager/api/v1"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/dynamic"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockRuntimeClientGetter creates a new instance of MockRuntimeClientGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeClientGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeClientGetter {
	mock := &MockRuntimeClientGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuntimeClientGetter is an autogenerated mock type for the RuntimeClientGetter type
type MockRuntimeClientGetter struct {
	mock.Mock
}

type MockRuntimeClientGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeClientGetter) EXPECT() *MockRuntimeClientGetter_Expecter {
	return &MockRuntimeClientGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRuntimeClientGetter
func (_mock *MockRuntimeClientGetter) Get(ctx context.Context, runtime v1.Runtime) (client.Client, error) {
	ret := _mock.Called(ctx, runtime)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.Runtime) (client.Client, error)); ok {
		return returnFunc(ctx, runtime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.Runtime) client.Client); ok {
		r0 = returnFunc(ctx, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1.Runtime) error); ok {
		r1 = returnFunc(ctx, runtime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuntimeClientGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRuntimeClientGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime v1.Runtime
func (_e *MockRuntimeClientGetter_Expecter) Get(ctx interface{}, runtime interface{}) *MockRuntimeClientGetter_Get_Call {
	return &MockRuntimeClientGetter_Get_Call{Call: _e.mock.On("Get", ctx, runtime)}
}

func (_c *MockRuntimeClientGetter_Get_Call) Run(run func(ctx context.Context, runtime v1.Runtime)) *MockRuntimeClientGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.Runtime
		if args[1] != nil {
			arg1 = args[1].(v1.Runtime)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuntimeClientGetter_Get_Call) Return(client1 client.Client, err error) *MockRuntimeClientGetter_Get_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockRuntimeClientGetter_Get_Call) RunAndReturn(run func(ctx context.Context, runtime v1.Runtime) (client.Client, error)) *MockRuntimeClientGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuntimeDynamicClientGetter creates a new instance of MockRuntimeDynamicClientGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeDynamicClientGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeDynamicClientGetter {
	mock := &MockRuntimeDynamicClientGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuntimeDynamicClientGetter is an autogenerated mock type for the RuntimeDynamicClientGetter type
type MockRuntimeDynamicClientGetter struct {
	mock.Mock
}

type MockRuntimeDynamicClientGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeDynamicClientGetter) EXPECT() *MockRuntimeDynamicClientGetter_Expecter {
	return &MockRuntimeDynamicClientGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRuntimeDynamicClientGetter
func (_mock *MockRuntimeDynamicClientGetter) Get(ctx context.Context, runtime v1.Runtime) (dynamic.Interface, discovery.DiscoveryInterface, error) {
	ret := _mock.Called(ctx, runtime)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dynamic.Interface
	var r1 discovery.DiscoveryInterface
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.Runtime) (dynamic.Interface, discovery.DiscoveryInterface, error)); ok {
		return returnFunc(ctx, runtime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.Runtime) dynamic.Interface); ok {
		r0 = returnFunc(ctx, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1.Runtime) discovery.DiscoveryInterface); ok {
		r1 = returnFunc(ctx, runtime)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(discovery.DiscoveryInterface)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, v1.Runtime) error); ok {
		r2 = returnFunc(ctx, runtime)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRuntimeDynamicClientGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRuntimeDynamicClientGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime v1.Runtime
func (_e *MockRuntimeDynamicClientGetter_Expecter) Get(ctx interface{}, runtime interface{}) *MockRuntimeDynamicClientGetter_Get_Call {
	return &MockRuntimeDynamicClientGetter_Get_Call{Call: _e.mock.On("Get", ctx, runtime)}
}

func (_c *MockRuntimeDynamicClientGetter_Get_Call) Run(run func(ctx context.Context, runtime v1.Runtime)) *MockRuntimeDynamicClientGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.Runtime
		if args[1] != nil {
			arg1 = args[1].(v1.Runtime)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuntimeDynamicClientGetter_Get_Call) Return(interfaceParam dynamic.Interface, discoveryInterface discovery.DiscoveryInterface, err error) *MockRuntimeDynamicClientGetter_Get_Call {
	_c.Call.Return(interfaceParam, discoveryInterface, err)
	return _c
}

func (_c *MockRuntimeDynamicClientGetter_Get_Call) RunAndReturn(run func(ctx context.Context, runtime v1.Runtime) (dynamic.Interface, discovery.DiscoveryInterface, error)) *MockRuntimeDynamicClientGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}
